[tool.mypy]
warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
python_version = '3.11'
explicit_package_bases = true 
# strict = true
no_implicit_optional = true
disallow_incomplete_defs = true
error_summary = false

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E741", "E501"]

[tool.pytest.ini_options]
markers = [
    "e2e",
    "no_sandbox",
]
