import logging
from typing_extensions import Protocol
from typing import cast

class Logger(Protocol):
    def trace(self, *args, **kwargs) -> None: ...
    def debug(self, *args, **kwargs) -> None: ...
    def info(self, *args, **kwargs) -> None: ...
    def warning(self, *args, **kwargs) -> None: ...
    def error(self, *args, **kwargs) -> None: ...
    def critical(self, *args, **kwargs) -> None: ...
    
def getLogger(name: str) -> Logger:
    return cast(
        Logger,
        logging.getLogger(name) 
    )
