name: "tests"
on: [push, pull_request, workflow_dispatch]
concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: cachix/cachix-action@v14
        with:
          name: ff
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run flake checks
        run: nix flake check --print-build-logs
